//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукты
    {
        public int ID_Product { get; set; }
        public string NameProduct { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public string DescriptionProduct { get; set; }
        public string ImageProduct { get; set; }
        public Nullable<int> FK_Product_Category { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
